build:
  stage: build
  image: rbonifaz/wahay-rpm-build:latest
  before_script:
    - "eval $(ssh-agent -s)"
    - 'ssh-add <(echo "$FEDORA_PACKAGING_PRIVATE_KEY")'
    - mkdir -p ~/.ssh; chmod 700 ~/.ssh
    - 'echo -e "[fedora.autonomia.digital]:4243,[185.108.78.22]:4243 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFE8IPu1LfB0ePyhgBFTyzXRNBZUiYa1ZaSnkFb746r3MgZQlfMhfxdMtrY3bKoiQ4i+HEUTCUN4BJ5n2PMdGz4=" > ~/.ssh/known_hosts'
    - chmod 644 ~/.ssh/known_hosts

  script:
    - git clone https://github.com/digitalautonomy/grumble.git grumble-0.0.1
    - cd grumble-0.0.1/
    - git checkout tags/v0.0.1
    - cd ..
    - tar zcf grumble-0.0.1.tar.gz grumble-0.0.1/
    - ./build_all.sh f30 f31 f32 f33 f34 f35 f36 f37 f38
