build:
  stage: build
  image: rbonifaz/wahay-rpm-build:latest
  #before_script:
  script:
    - git clone https://github.com/digitalautonomy/grumble.git
    - cd grumble/
    - git checkout c109af8d88b4b9cb77afe1f18572c66027cf8c0b
    - cd ..
    - mv grumble/ grumble-c109af8d88b4b9cb77afe1f18572c66027cf8c0b
    - tar zcf grumble-c109af8d88b4b9cb77afe1f18572c66027cf8c0b.tar.gz grumble-c109af8d88b4b9cb77afe1f18572c66027cf8c0b/
    - mkdir f30 f31
    - fedpkg --release f30 local
    - 'find . -name "*fc30*.rpm -exec mv {} f30 \;'
    - fedpkg --release f31 local
    - 'find . -name "*fc30*.rpm" -exec mv {} f31 \;'
  artifacts:
    paths:
      - 'f30/*.rpm'
      - 'f31/*.rpm'
