# Generated by go2rpm 1
%bcond_without check

# https://github.com/digitalautonomy/grumble
%global goipath         github.com/digitalautonomy/grumble
%global commit          c109af8d88b4b9cb77afe1f18572c66027cf8c0b

%gometa

%global common_description %{expand:
Alternative Mumble server - this fork makes it possible to use Grumble as a
library.}

%global golicenses      LICENSE
%global godocs          AUTHORS README.md pkg/cryptstate/testgen/README

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Alternative Mumble server - this fork makes it possible to use Grumble as a library

# Upstream license specification: BSD-3-Clause
License:        BSD
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/golang/protobuf/proto)
BuildRequires:  golang(github.com/gorilla/websocket)
BuildRequires:  golang(golang.org/x/crypto/nacl/secretbox)

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done
for cmd in pkg/mumbleproto; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc AUTHORS README.md pkg/cryptstate/testgen/README
%{_bindir}/*

%gopkgfiles

%changelog
* Mon Mar 16 12:37:43 -05 2020 rafael <rafael@autonomia.digital> - 0-0.1.20200316gitc109af8
- Initial package

